"""Compare persistence and neighbor propagation without fitting case outcomes."""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
import sys
from typing import Iterable


ROOT = Path(__file__).resolve().parents[3]
STUDY = ROOT / "studies" / "afghanistan_2004_2021"
SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from identify_spatial_reproduction import (  # noqa: E402
    build_risk_set,
    dose_response,
    episode_metrics,
    lead_placebo_risk_difference,
)


def transition_metrics(active: set[tuple[str, int]], areas: set[str],
                       neighbors: dict[str, set[str]]) -> dict:
    if not active:
        return {"active_cells": 0, "same_area_renewal_n": 0,
                "same_area_renewal_rate": None, "neighbor_exposures": 0,
                "neighbor_activation_rate": None, "neighbor_unexposed_n": 0,
                "neighbor_unexposed_activation_rate": None,
                "neighbor_activation_risk_difference": None,
                "episode_metrics": episode_metrics(active, areas),
                "neighbor_activation_dose_response": {},
                "lead_placebo_risk_difference": None,
                "same_area_renewal_causal_claim_licensed": False,
                "neighbor_activation_causal_claim_licensed": False}
    last_week = max(week for _, week in active)
    eligible = {(area, week) for area, week in active if week < last_week}
    renewed = sum((area, week + 1) in active for area, week in eligible)
    exposures: set[tuple[str, int]] = set()
    for area, week in eligible:
        for neighbor in neighbors.get(area, set()):
            if neighbor in areas and (neighbor, week) not in active:
                exposures.add((neighbor, week + 1))
    activated = sum(cell in active for cell in exposures)

    # A raw exposed activation rate is not evidence of geographic contagion:
    # areas may activate at a high background rate even without an active
    # neighbor.  Construct the same one-step risk among inactive source cells
    # that had no active neighbor, so the diagnostic exposes the comparison
    # risk rather than silently treating zero as the counterfactual.
    first_week = min(week for _, week in active)
    unexposed: set[tuple[str, int]] = set()
    for week in range(first_week, last_week):
        active_now = {area for area, observed_week in active if observed_week == week}
        for area in areas:
            if area in active_now:
                continue
            if any(neighbor in active_now for neighbor in neighbors.get(area, set())):
                continue
            unexposed.add((area, week + 1))
    unexposed_activated = sum(cell in active for cell in unexposed)
    exposed_rate = activated / len(exposures) if exposures else None
    unexposed_rate = unexposed_activated / len(unexposed) if unexposed else None
    risk_rows = build_risk_set(active, areas, neighbors)
    lead_placebo = lead_placebo_risk_difference(active, areas, neighbors)
    return {
        "active_cells": len(active),
        "same_area_renewal_n": len(eligible),
        "same_area_renewal_rate": renewed / len(eligible) if eligible else None,
        "neighbor_exposures": len(exposures),
        "neighbor_activation_rate": exposed_rate,
        "neighbor_unexposed_n": len(unexposed),
        "neighbor_unexposed_activation_rate": unexposed_rate,
        "neighbor_activation_risk_difference": (
            exposed_rate - unexposed_rate
            if exposed_rate is not None and unexposed_rate is not None else None
        ),
        "episode_metrics": episode_metrics(active, areas),
        "neighbor_activation_dose_response": dose_response(risk_rows),
        "lead_placebo_risk_difference": lead_placebo["risk_difference"],
        "same_area_renewal_causal_claim_licensed": False,
        "neighbor_activation_causal_claim_licensed": False,
        "identification_warning": (
            "Same-area renewal is a binary-cell continuity diagnostic, not proof of a "
            "continuous episode. Neighbor activation and its exposed-unexposed risk "
            "difference are descriptive associations and can be generated by spatial "
            "frailty, topology, degree, or common shocks. Causal propagation requires "
            "the preregistered synthetic recovery and placebo battery."
        ),
    }


def overlap_metrics(observed: set[tuple[str, int]], modeled: set[tuple[str, int]]) -> dict[str, float | int]:
    intersection = len(observed & modeled)
    return {
        "intersection": intersection,
        "historical_sensitivity": intersection / len(observed) if observed else 0.0,
        "model_precision": intersection / len(modeled) if modeled else 0.0,
        "jaccard": intersection / len(observed | modeled) if observed or modeled else 1.0,
    }


def province_neighbors(case: dict) -> tuple[set[str], dict[str, set[str]]]:
    district_to_province = {
        row["district_id"]: row["container_ids"]["province"] for row in case["districts"]
    }
    locality_to_province = {
        row["locality_id"]: district_to_province[row["district_id"]] for row in case["localities"]
    }
    areas = set(locality_to_province.values())
    result = {area: set() for area in areas}
    for locality, adjacent in case["adjacency"].items():
        source = locality_to_province[locality]
        for neighbor in adjacent:
            target = locality_to_province[neighbor]
            if source != target:
                result[source].add(target)
                result[target].add(source)
    return areas, result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--runs-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    run_paths = sorted(args.runs_dir.glob("seed_*_taliban_*.json"))
    if not run_paths:
        raise SystemExit("no completed transfer trajectories found")
    runs = [json.loads(path.read_text(encoding="utf-8")) for path in run_paths]
    horizon = min(float(run["horizon_days"]) for run in runs)
    case = json.loads((STUDY / "config" / "case_environment.json").read_text(encoding="utf-8"))
    areas, neighbors = province_neighbors(case)
    observed: set[tuple[str, int]] = set()
    with (STUDY / "data" / "processed" / "province_week_panel.csv").open(encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            if int(row["week_index"]) * 7 <= horizon and int(row["taliban_state_active"]):
                observed.add((row["province_id"], int(row["week_index"])))
    report = {
        "schema_version": "1.1.0",
        "status": "diagnostic_not_calibration",
        "horizon_days": horizon,
        "historical": transition_metrics(observed, areas, neighbors),
        "runs": [],
        "interpretation": (
            "Binary renewal, neighbor activation, and overlap are descriptive diagnostics. "
            "Episode continuity, dose response, temporal placebo behavior, synthetic null "
            "recovery, and parent-attributed genealogy are required before any persistence "
            "or propagation mechanism claim; none of these diagnostics authorize parameter fitting."
        ),
    }
    for run, path in zip(runs, run_paths):
        modeled = {(row["province_id"], int(row["week_index"]))
                   for row in run["violence_validation"]["recorded_active_cells"]}
        report["runs"].append({
            "file": path.name,
            "strength": run["taliban_initial_strength"],
            **transition_metrics(modeled, areas, neighbors),
            **overlap_metrics(observed, modeled),
        })
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
