[package]
name = "pineland-io"
version = "1.0.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = []
parquet = ["dep:parquet"]

[dependencies]
pineland-core = { path = "../pineland-core" }
pineland-model = { path = "../pineland-model" }
parquet = { version = "59.3.0", default-features = false, optional = true }

[lib]
path = "src/lib.rs"
